name: build
on:
  schedule:
    - cron: "30 16 * * *"
  push:
    branches:
      - main
  pull_request:

env:
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  BASE_IMAGE_REGISTRY: quay.io/fedora-ostree-desktops
  BASE_IMAGE: silverblue
  BASE_IMAGE_VERSION: 42

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build image
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: |
            ./Containerfile
          build-args: |
            BASE_IMAGE_REGISTRY=${{ env.BASE_IMAGE_REGISTRY }}
            BASE_IMAGE=${{ env.BASE_IMAGE }}
            BASE_IMAGE_VERSION=${{ env.BASE_IMAGE_VERSION }}
          image: silverblue
          tags: latest

      - name: Push To GHCR
        uses: redhat-actions/push-to-registry@v2
        id: push
        if: github.event_name != 'pull_request'
        env:
          REGISTRY_USER: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ github.token }}
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          extra-args: |
            --disable-content-trust

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
